[package]
name = "asteroids"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
log = "0.4.8"
log4rs = "0.11"
ggez = "0.5.1"
rand = "0.7"

# [target.x86_64-pc-windows-gnu]
# linker = "x86_64-w64-mingw32-gcc"
# ar = "x86_64-w64-mingw32-gcc-ar"
